elasticsearch:
  hosts:
    - elasticsearch-coordinating-only.logging.svc.cluster.local
  port: 9200
ingress:
  enabled: true
  hostname: kibana.juan.cluster     # To be customized
  certManager: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: self-signed
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
