alertmanager:
  enabled: true
  ingress:
    enabled: false
prometheus:
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    hostname: prometheus.juan.cluster     # To be customized
