wordpressUsername: admin               # To be customized 
wordpressPassword: adminpass           # To be customized
wordpressEmail: user@example.com       # To be customized
wordpressFirstName: Juan               # To be customized
wordpressLastName: Ariza Toledano      # To be customized
wordpressBlogName: Juan's Blog!        # To be customized
wordpressScheme: https
wordpressConfigureCache: true
allowEmptyPassword: false
replicaCount: 1
livenessProbe:
  enabled: true
  httpGet:
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
readinessProbe:
  enabled: true
  httpGet:
    httpHeaders:
    - name: X-Forwarded-Proto
      value: https
persistence:
  accessModes:
    - ReadWriteMany
  storageClass: nfs
service:
  type: ClusterIP
ingress:
  enabled: true
  certManager: true
  hostname: wordpress.juan.cluster     # To be customized
  annotations:
    kubernetes.io/ingress.class: nginx
pdb:
  create: true
  minAvailable: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 11
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
mariadb:
  enabled: false
externalDatabase:
  user: bn_wordpress                   # To be customized
  password: wordpresspassword          # To be customized
  database: bitnami_wordpress          # To be customized
  host: mariadb-galera.wordpress.svc.cluster.local
  port: 3306
memcached:
  enabled: false
externalCache:
  host: memcached.wordpress.svc.cluster.local
  port: 11211
